package Dominoes;

import javafx.scene.input.MouseEvent;

//***********************************
// Ryan Hughes
//
// This class handles the action listening for the
// canvas and the turn taking for the human player.
// It is associated with the human player
//***********************************

public class PlayerListener
{
  private Player player;
  private Domino pressed;
  private int pressedIndex;
  private Controller controller;

  /**
   * Constructor
   * @param player the human player
   * @param controller the controller for the game
   */
  public PlayerListener(Player player, Controller controller)
  {
    this.player = player;
    this.controller = controller;
  }

  /**
   * This method will "pick up" a domino if the click is on a
   * domino, it will draw a domino if the boneyard was clicked,
   * and it will ignore the click if it is not a domino or the boneyard
   * @param mouseEvent the MouseEvent generated by the ActionListener
   */
  public void handlePress(MouseEvent mouseEvent)
  {
    Object[] hand = player.getHand().toArray();
    double clickX = mouseEvent.getX();
    double clickY = mouseEvent.getY();

    for(int i = 0; i < hand.length; i++)
    {
      double difx = clickX - ((Domino)hand[i]).getX();
      double dify = clickY - ((Domino)hand[i]).getY();
      if(difx > 0 && difx < Display.DOMINO_WIDTH && // if a domino was clicked
         dify > 0 && dify < Display.DOMINO_HEIGHT)
      {
        ((Domino)hand[i]).pickUp();
        pressed = (Domino)hand[i];
        pressedIndex = i;
        player.printHand(1);
        player.play(player.getHand().indexOf(pressed));
      }
    }

    double difx = clickX - Display.BONEYARD_X;
    double dify = clickY - Display.BONEYARD_Y;
    if(difx > 0 && difx < Display.BONEYARD_WIDTH && // if the boneyard was clicked
       dify > 0 && dify < Display.BONEYARD_HEIGHT)
    {
      player.draw();
      player.printHand(1);
    }
  }

  /**
   * This method will update the x and y coordinates of the pressed
   * domino so that it is dragged around the canvas with the mouse
   * @param mouseEvent the MouseEvent passed from the ActionListener
   */
  public void handleDrag(MouseEvent mouseEvent)
  {
    if(pressed != null)
    {
      pressed.setX((int) mouseEvent.getX());
      pressed.setY((int) mouseEvent.getY());
      player.printHand(1);
      player.printBoard();
      player.printBones();
      pressed.display(1);
    }
  }

  /**
   * This method handles th logic for putting a domino down.
   * If the domino is dropped on the left or right side of the
   * board, close enough to overlap with the yellow squares it will
   * be added to the appropriate side. if it is dropped anywhere else,
   * the domino will be returned to it's position in the hand.
   * BUG: if the domino is dropped on an end where it can not be
   * placed, it will just sit there
   * BUG: the hand does not always act appropriately when a domino
   * is returned after being dropped off the board
   * @param mouseEvent the MouseEvent passed from the ActionListener
   */
  public void handleRelease(MouseEvent mouseEvent)
  {
    if(pressed != null)
    {
      pressed.putDown();
      int leftx = player.getBoard().getLeftx();
      int lefty = player.getBoard().getLefty();
      int rightx = player.getBoard().getRightx();
      int righty = player.getBoard().getRighty();
      if (isCloseEnough(pressed.getX(), leftx, pressed.getY(), lefty))
      {
        if (player.getBoard().placeLeft(pressed))
        {
          pressed = null;
          controller.run();
        }
        else
        {
          player.draw(pressed);
          pressed = null;
          pressedIndex = -1;
        }
      }
      else if (isCloseEnough(pressed.getX(), rightx, pressed.getY(), righty))
      {
        if (player.getBoard().placeRight(pressed))
        {
          pressed = null;
          controller.run();
        }
        else
        {
          player.draw(pressed);
          pressed = null;
          pressedIndex = -1;
        }
      }
      else
      {
        pressed.setX(((pressedIndex + 1) * Display.DOMINO_HBUFFER) +
          (pressedIndex * Display.DOMINO_WIDTH));
        pressed.setY(Display.SCREEN_HEIGHT - Display.HAND_HEIGHT + Display.DOMINO_VBUFFER);
        player.draw(pressed);
        pressed = null;
        pressedIndex = -1;
      }
    }
    player.printBoard();
    player.printHand(1);
    player.printBones();
  }

  private boolean isCloseEnough(int x1, int x2, int y1, int y2)
  {
    if(Math.abs(x2 - x1) < Display.DOMINO_WIDTH &&
       Math.abs(y2 - y1) < Display.DOMINO_HEIGHT)
      return true;
    return false;
  }
}
